apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-redis
  namespace: argocd
  labels:
    type: dep
spec:
  project: myproject-production
  source:
    repoURL: git@github.com:melalj/gitops-sample.git
    targetRevision: HEAD
    path: charts/dep/redis
    helm:
      releaseName: redis
      valueFiles:
      - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: production
