apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: production # edit this for staging
type: Opaque
data:
  MY_SECRET_VAR: "Ym9uam91ciBtYWRhbWU=" # base64 encoded
  REDIS_URL: "cmVkaXM6Ly86cmVkaXMtbXlwcm9qZWN0LXBhc3N3b3JkQHJlZGlzLW1hc3Rlcjo2Mzc5" # base64 of: redis://:redis-myproject-password@redis-master:6379
  GOOGLE_CREDENTIALS: "****" # base64 encoded
